fix: preview image radius
ejbills/DockDoor pull request #87
Opened 2024-07-07 02:23 UTC by ShlomoCode

Before:
When using a dark theme in System Settings, there are white corners around the preview image
![CleanShot 2024-07-07 at 05 21 35@2x](https://github.com/ejbills/DockDoor/assets/78599753/4498b3b0-4133-4b0e-8cee-9afdc2aff877)
![CleanShot 2024-07-07 at 05 21 39@2x](https://github.com/ejbills/DockDoor/assets/78599753/5c8087a3-908e-4998-9e1f-fbe7c01e96c8)
After:
![CleanShot 2024-07-07 at 05 18 19@2x](https://github.com/ejbills/DockDoor/assets/78599753/54c50e4d-8359-411b-8b65-009b2cb564f0)
![CleanShot 2024-07-07 at 05 20 19@2x](https://github.com/ejbills/DockDoor/assets/78599753/576f7f7a-5e6a-4a29-b1bc-e79145f8afd5)

2024-07-07 02:23 UTC, ShlomoCode commented
I am open to other ways to solve the problem.

2024-07-08 14:42 UTC, ejbills requested changes
Please move the radius change to here, rather than making a new modifier. This controls the rounded edge for images.

2024-07-08 15:24 UTC, ejbills approved these changes

2024-07-08 15:24 UTC, merged

2024-07-08 15:48 UTC, ShlomoCode commented
Each software seems to have a different radius. For example, Slack has a much sharper curve than iTerm, and with the additional radius it is cut:
![CleanShot 2024-07-08 at 18 31 45@2x](https://github.com/ejbills/DockDoor/assets/78599753/da187c09-9569-492d-9669-42535226071f)
![CleanShot 2024-07-08 at 18 29 24@2x](https://github.com/ejbills/DockDoor/assets/78599753/076400d0-f128-460b-8ec0-9662d0b16ee6)

I'll post a better fix soon.